### ISSUE TITLE
[Suggestion]: Bind any key to mousewheel slot-cycling

### ISSUE THREAD

**Issue by Muhlex** [Fuzss/slotcycler#1]
### Suggestion (Required)

Any chance to allow different keys other than the regular modifiers (Alt, Shift, Ctrl) for the cycling via mousewheel? I think this is the most useful hotbar cycling mod due to the nice preview, but I would like to bind this to another key.

Is there a technical reason this key isn't simply in the Keybindings options screen anyway, like the ones to cycle manually?

**Comment by Fuzss** [comment]
Yeah, the problem with this is that vanilla doesn't allow the same key to be assigned to different actions when the keybindings system is used. So let's say you bind the Slot Cycler key to shift, but also use it for crouching -> crouching no longer works suddenly (not sure if this is exactly the case in that scenario, but this is basically the problem, already had this happen on another mod of mine with the `Tab` key which normally triggers the multiplayer player list).

Forge fixes this issue by overhauling big parts of the key bindings implementation, but Fabric doesn't seem to offer any equivalent, and I'm not just gonna do this for Forge.
