### ISSUE TITLE
[Suggestion]: 1.20.2 Version

### ISSUE THREAD

**Issue by lullaby6** [Fuzss/slotcycler#13]
### Mod Loader (Optional)

⸺

### Minecraft Version(s) (Optional)

1.20.2

### Suggestion (Required)

Hi, I would like to ask you if you can make a version of the mod for version 1.20.2, since a famous server called Wynncraft has custom mods for 1.20.2 and I wanted to put together a modpack of those mods along with the great Slot Cycler mod, so I ask you if it is not too difficult, thanks for reading.

**Comment by Fuzss** [comment]
1.20.2 is unfortunately no longer planned due to time constraints.
