### ISSUE TITLE
[Bug]: Compatibility Issue, SlotCycler x Deselect

### ISSUE THREAD

**Issue by 533kr** [Fuzss/slotcycler#20]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.1

### Minimal Setup (Required)

No

### Notes (Required)

I'm filing this with both Slot Cycler and the Deselect mod since I'm not where exactly the failure occurs, but with both Slot Cycler and [Deselect](https://modrinth.com/mod/deselect) installed, pressing the deselect keybind causes an immediate crash. The resulting crashlog calls out Slot Cycler specifically.

Crashlog file: 
[crash-2024-09-14_16.02.15-client.txt](https://github.com/user-attachments/files/17003669/crash-2024-09-14_16.02.15-client.txt)

### latest.log (Required)

https://gist.github.com/533kr/a24a79c5b1e235bf87881ff230860cf1

**Comment by Fuzss** [comment]
Seems to have been fixed on their end.
