### ISSUE TITLE
[Bug]: Items moving to random places in the inventory when attempting to cycle

### ISSUE THREAD

**Issue by ItsCre3per** [Fuzss/slotcycler#7]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

Current behavior: When a hotbar slot is empty and a slot cycler key is pressed, the item that should be cycled into the hotbar is instead sent to a different place in the inventory, as if shift-clicked from the hotbar.
Steps to reproduce: 
1. Put a few items in one column of the inventory. 
2. Empty the corresponding hotbar slot to the column.
3. Attempt to cycle one of the items into the hotbar. 
Expected: Following these steps, the cycled item should appear in the corresponding hotbar slot.

**Comment by ItsCre3per** [comment]
Bug is produced by another mod.

**Comment by Fuzss** [comment]
Which one?

**Comment by ItsCre3per** [comment]
Item Scroller, it has a hidden feature where items that are picked up go into the inventory instead of the hotbar.
