### ISSUE TITLE
[Bug]: No bundle sounds

### ISSUE THREAD

**Issue by MaxCross2500** [Fuzss/slotcycler#9]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

No sounds of adding item to bundle or removing item from bundle.

**Comment by MaxCross2500** [comment]
upd: The same issue also appears when I have `Easy Shulker Boxes` enabled. Having at least one of those mods disables bundle sounds.

**Comment by Fuzss** [comment]
Both mods use the same internal library (Puzzles Api).

From that mod there is a config `iteminteractions-client.toml` with an option `disableInteractionSounds` which you can enable to restore bundle sounds. The sounds are disabled by default as the drag across items feature from that module does spam the bundle sound which is quite annoying.
